/** Health check response from the backend /health endpoint. */
export interface HealthResponse {
  status: string;
  openai_endpoint_host?: string | null;
  openai_endpoint_mode?: string | null;
  timestamp: string;
}

/** Response returned when a pipeline run is triggered via /run endpoints. */
export interface RunResponse {
  task_id: string;
  message: string;
}

export interface QueueJobResponse {
  id: string;
  kind: string;
  payload: Record<string, unknown>;
  status: string;
  created_at: string;
  started_at: string | null;
  finished_at: string | null;
  error: string | null;
  result: Record<string, unknown> | null;
}

export interface QueueSnapshotResponse {
  current: QueueJobResponse | null;
  queued: QueueJobResponse[];
  recent: QueueJobResponse[];
}

/** Summary information for a single video returned by the videos list endpoint. */
export interface VideoItemResponse {
  youtube_video_id: string;
  title: string;
  published_at: string;
  has_report: boolean;
  latest_run_status: string | null;
}

/** Extended video row with pipeline run status and progress details. */
export interface VideoStatusRow {
  video_id: number;
  youtube_video_id: string;
  title: string;
  published_at: string;
  has_report: boolean;
  has_appeal_report: boolean;
  run_status: string | null;
  run_status_text: string;
  progress_pct: number;
  stage_current: number;
  stage_total: number;
  stage_label: string | null;
  has_error: boolean;
  appeal_run_status: string | null;
}

/**
 * Aggregated summary for a single comment topic cluster,
 * including sentiment, positions, and representative quotes.
 */
export interface TopicSummary {
  cluster_key: string;
  label: string;
  description: string;
  author_actions: string[];
  sentiment: string;
  emotion_tags: string[];
  intent_distribution: Record<string, number>;
  representative_quotes: string[];
  question_comments: string[];
  positions: TopicPosition[];
  size_count: number;
  share_pct: number;
  weighted_share: number;
  is_emerging: boolean;
  source: "episode_topic" | "comment_topic";
  coherence_score: number;
  centroid: number[] | null;
  assignment_confidence: number;
  ambiguous_share_pct: number;
  soft_assignment_notes: string[];
}

export interface ActionItem {
  topic_cluster_key: string;
  topic_label: string;
  share_pct: number;
  priority: number;
  action: string;
  key_criticism: string;
  key_question: string;
}

/** A distinct viewpoint position within a topic cluster. */
export interface TopicPosition {
  key: string;
  title: string;
  summary: string;
  markers: string[];
  prototype: string;
  count: number;
  pct: number;
  weighted_count: number;
  weighted_pct: number;
  comments: string[];
  is_undetermined: boolean;
  is_author_disagreement: boolean;
  coherence_score: number;
  single_claim_passed: boolean;
}

/**
 * Full daily briefing generated by the analysis pipeline,
 * containing topics, actions, risks, and representative quotes.
 */
export interface DailyBriefing {
  video_id: string;
  video_title: string;
  published_at: string;
  mode: string;
  executive_summary: string;
  top_topics: TopicSummary[];
  actions_for_tomorrow: string[];
  action_items: ActionItem[];
  misunderstandings_and_controversies: string[];
  audience_requests_and_questions: string[];
  risks_and_toxicity: string[];
  representative_quotes: string[];
  author_disagreement_comments: string[];
  trend_vs_previous: string[];
  metadata: Record<string, unknown>;
}

export interface TopicPipelineDiagnostics {
  embedding_model?: string;
  embedding_provider?: string;
  cluster_assignment_confidence_avg?: number;
  cluster_ambiguous_comment_share?: number;
  cluster_reduction_summary?: Record<string, unknown>;
  cluster_parameter_summary?: Record<string, unknown>;
}

export interface TopicTrendPoint {
  video_id: string;
  video_title: string;
  published_at: string;
  share_pct: number;
  weighted_share: number;
  matched_topic_label: string;
  similarity: number;
  is_current: boolean;
}

export interface TopicTrendSeries {
  cluster_key: string;
  topic_label: string;
  summary: string;
  points: TopicTrendPoint[];
}

/** Report payload containing the briefing data along with rendered markdown and HTML. */
export interface ReportResponse {
  video_id: string;
  generated_at: string;
  markdown: string;
  html: string;
  briefing: DailyBriefing;
}

/** A single OpenAI API call log entry with token counts and estimated cost. */
export interface BudgetEntry {
  provider: string;
  model: string;
  task: string;
  tokens_input: number;
  tokens_output: number;
  estimated_cost_usd: number;
  created_at: string;
}

/** Daily budget usage summary including spend, remaining balance, and call entries. */
export interface BudgetUsageResponse {
  usage_date: string;
  spent_usd: number;
  tokens_used: number;
  entries: BudgetEntry[];
}

/** Current runtime settings for the scheduler beat and pipeline. */
export interface RuntimeSettingsResponse {
  beat_enabled: boolean;
  beat_time_kyiv: string;
  updated_at: string | null;
  author_name: string;
  openai_chat_model: string;
  embedding_mode: string;
  local_embedding_model: string;
  cluster_max_count: number;
  max_comments_per_video: number;
  youtube_include_replies: boolean;
  openai_enable_polish_call: boolean;
}

export interface SetupStatusResponse {
  is_configured: boolean;
  has_openai_api_key: boolean;
  has_youtube_api_key: boolean;
  has_playlist_id: boolean;
  has_youtube_oauth_client_id: boolean;
  has_youtube_oauth_client_secret: boolean;
  has_youtube_oauth_refresh_token: boolean;
  runtime_env_path: string;
}

export interface SetupRequest {
  openai_api_key: string;
  youtube_api_key: string;
  youtube_playlist_id?: string;
  youtube_oauth_client_id?: string;
  youtube_oauth_client_secret?: string;
  youtube_oauth_refresh_token?: string;
}

export interface SetupUpdateRequest {
  openai_api_key?: string;
  youtube_api_key?: string;
  youtube_playlist_id?: string;
  youtube_oauth_client_id?: string;
  youtube_oauth_client_secret?: string;
  youtube_oauth_refresh_token?: string;
}

/** Partial update payload for runtime settings (all fields optional). */
export type RuntimeSettingsUpdateRequest = Partial<
  Omit<RuntimeSettingsResponse, "updated_at">
>;

/** Detailed report response with author name, topic comments, and position breakdowns. */
export interface ReportDetailResponse {
  report: ReportResponse;
  author_name: string;
  topic_comments: Record<string, string[]>;
  topic_question_comments: Record<string, string[]>;
  topic_positions: Record<string, TopicPosition[]>;
  topic_trends: TopicTrendSeries[];
}

/** A single comment item within an appeal analytics block. */
export interface AppealBlockItem {
  comment_id: number;
  author_name: string | null;
  text: string;
  score: number | null;
  author_channel_id?: string | null;
}

/** Group of comments from the same author. */
export interface AppealAuthorGroup {
  author_name: string;
  author_channel_id: string | null;
  banned_user_id: number | null;
  is_banned_active: boolean;
  youtube_banned: boolean;
  comment_count: number;
  comments: AppealBlockItem[];
}

/** One of the 5 classification blocks. */
export interface AppealBlock {
  block_type: string;
  display_label: string;
  sort_order: number;
  item_count: number;
  authors: AppealAuthorGroup[];
  items: AppealBlockItem[];
}

/** Full appeal analytics response for a video. */
export interface AppealAnalyticsResponse {
  video_id: string;
  video_title: string;
  generated_at: string;
  total_comments: number;
  classified_comments: number;
  blocks: AppealBlock[];
}

/** All comments by a specific author under a video. */
export interface AuthorCommentsResponse {
  author_name: string;
  video_id: string;
  comments: AppealBlockItem[];
}

/** Toxic comment item for manual review. */
export interface ToxicReviewItem {
  comment_id: number;
  author_name: string | null;
  text: string;
  confidence_score: number;
  insult_target: string | null;
}

/** Response for toxic comments requiring manual review. */
export interface ToxicReviewResponse {
  video_id: string;
  video_title: string;
  total_review_items: number;
  items: ToxicReviewItem[];
}

/** Response after banning a user. */
export interface BanUserResponse {
  status: string;
  banned_user_id: number | null;
  youtube_banned: boolean;
  youtube_error: string | null;
  csv_saved: boolean;
}

export interface UnbanUserResponse {
  status: string;
  banned_user_id: number | null;
  youtube_unbanned: boolean;
  youtube_error: string | null;
}

/** Response with video guests list. */
export interface VideoGuestsResponse {
  video_id: string;
  guest_names: string[];
}
